site_name: Lutienpeist重开的计算机生活

nav:
  - 封面: index.md 
  - CS自学指南: 
    - 前言: CSself/first.md
    - Chap1-Crash Course Computer Science: 
      - 本章概述: CSself/Chap1intro/intro.md
      - 历史&硬件发展：从算盘到电子计算机，从晶体管到CPU: CSself/Chap1intro/05.md
      - 早期的编程发展——从接线板到面向对象: CSself/Chap1intro/510.md
      - 计算机的早期发展——从集成电路到操作系统，从文件系统到屏幕: CSself/Chap1intro/600.md
      - 计算机图形学: CSself/Chap1intro/710.md
      - 计算机网络学: CSself/Chap1intro/790.md
      - 计算机安全学: CSself/Chap1intro/880.md
      - 计算机科学其它分支: CSself/Chap1intro/996.md
    - Chap2-The Missing Semester of Your CS Education:
      - 本章概述: CSself/Chap2lost/intro.md
      - Lecture1 shell: CSself/Chap2lost/1.md
      - Lecture2 Shell 工具和脚本: CSself/Chap2lost/2.md
      - Lecture3 Vim: CSself/Chap2lost/3.md
      - Lecture4 Data Wrangling: CSself/Chap2lost/4.md
      - Lecture5 命令行环境: CSself/Chap2lost/5.md
      - Lecture6 版本控制: CSself/Chap2lost/6.md
      - Lecture7 调试及性能分析: CSself/Chap2lost/7.md
      - Lecture8 元编程: CSself/Chap2lost/8.md
      - Lecture9 安全与密码学: CSself/Chap2lost/9.md
      - Lecture10 大杂烩: CSself/Chap2lost/10.md
  - ZJU_Courses:
    - 前言: ZJU_Courses/前言.md
    - 数学基础课程: 
      - 数学分析Ⅰ(H): ZJU_Courses/math/shufen1/不要忘记反证法.md
      - 数学分析Ⅱ(H): building.md
      - 线性代数Ⅱ(H): building.md
      - 概率论与数理统计: building.md
      - 离散数学(CKC):
        - 课堂规则: ZJU_Courses/math/离散数学/DM.md
        - 第一课: ZJU_Courses/math/离散数学/DM1.md
    - CS基础课程:
      - 数字逻辑设计: ZJU_Courses/CSbasic/数字逻辑设计/shuluo.md
      - 数据结构基础: 
        - 前言: ZJU_Courses/CSbasic/FDS/qianyan.md
        - 基础知识: ZJU_Courses/CSbasic/FDS/基础知识.md
        - 线性结构: ZJU_Courses/CSbasic/FDS/线性结构.md
        - 树: ZJU_Courses/CSbasic/FDS/树.md
        - 图: ZJU_Courses/CSbasic/FDS/图.md
        - 排序: ZJU_Courses/CSbasic/FDS/排序.md
        - 错题: ZJU_Courses/CSbasic/FDS/题目.md
      - 高级数据结构与算法分析:
        - 前言: ZJU_Courses/CSbasic/ADS/前言.md
        - Lecture 1: ZJU_Courses/CSbasic/ADS/1.md
        - Lecture 2: ZJU_Courses/CSbasic/ADS/2.md
      - 数据库系统:
        - 前言: ZJU_Courses/CSbasic/DBS/前言.md
        - Lecture 1: ZJU_Courses/CSbasic/DBS/Chap1.md
        - Lecture 2: ZJU_Courses/CSbasic/DBS/Chap2.md
      - 计算机组成: 
        - 前言: ZJU_Courses/CSbasic/CO/前言.md
        - Lecture 1+2.2: ZJU_Courses/CSbasic/CO/1+2.1.md
        - Lecture 2.2: ZJU_Courses/CSbasic/CO/2.2.md
      - 面向对象程序:
        - 前言: ZJU_Courses/CSbasic/OOP/前言.md
        - Chapter 1: ZJU_Courses/CSbasic/OOP/Chap1.md
    - 其它有意思的课程:
      - 博弈论基础: building.md
      - 马克思主义原理(H): ZJU_Courses/其它有意思的课程/马原/马原.md
      - 无线网络应用: ZJU_Courses/其它有意思的课程/无线网络应用/无线网络应用.md
      - 微信小程序综合实践: building.md
      - 生命科学导论(H): building.md
  - Programming Language:
    - C++ Programming Tutorial:
      - Introduction: Programming Language/C++ Programming Tutorial/0.md
      - Basics: Programming Language/C++ Programming Tutorial/1.md
      - More Basics: Programming Language/C++ Programming Tutorial/2.md
      - Object-Oriented Programming (OOP) in C++: Programming Language/C++ Programming Tutorial/3.md

theme:
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - navigation.instant
    - navigation.tracking    
    - navigation.tabs
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

plugins:
  - statistics

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js
