nav:
- building: .\building.md
- CSself:
  - Chap1intro:
    - '05': .\CSself\Chap1intro\05.md
    - '510': .\CSself\Chap1intro\510.md
    - '600': .\CSself\Chap1intro\600.md
    - '710': .\CSself\Chap1intro\710.md
    - '790': .\CSself\Chap1intro\790.md
    - '880': .\CSself\Chap1intro\880.md
    - '996': .\CSself\Chap1intro\996.md
    - intro: .\CSself\Chap1intro\intro.md
  - Chap2lost:
    - '1': .\CSself\Chap2lost\1.md
    - '10': .\CSself\Chap2lost\10.md
    - '2': .\CSself\Chap2lost\2.md
    - '3': .\CSself\Chap2lost\3.md
    - '4': .\CSself\Chap2lost\4.md
    - '5': .\CSself\Chap2lost\5.md
    - '6': .\CSself\Chap2lost\6.md
    - '7': .\CSself\Chap2lost\7.md
    - '8': .\CSself\Chap2lost\8.md
    - '9': .\CSself\Chap2lost\9.md
    - intro: .\CSself\Chap2lost\intro.md
  - Chap3CS70:
    - '0': .\CSself\Chap3CS70\0.md
  - first: .\CSself\first.md
  - tool:
    - git: .\CSself\tool\git.md
    - intro: .\CSself\tool\intro.md
    - mine: .\CSself\tool\mine.md
- index: .\index.md
- SRTP:
  - index: .\SRTP\index.md
  - Intro to Large Language Models:
    - '1': .\SRTP\Intro to Large Language Models\1.md
  - 文献阅读:
    - 2302.12173v2: .\SRTP\文献阅读\2302.12173v2.md
- ZJU_Courses:
  - CSbasic:
    - ADS:
      - spring:
        - Lecture:
          - '1': .\ZJU_Courses\CSbasic\ADS\spring\Lecture\1.md
          - '2': .\ZJU_Courses\CSbasic\ADS\spring\Lecture\2.md
          - '3': .\ZJU_Courses\CSbasic\ADS\spring\Lecture\3.md
          - '4': .\ZJU_Courses\CSbasic\ADS\spring\Lecture\4.md
          - '5': .\ZJU_Courses\CSbasic\ADS\spring\Lecture\5.md
          - '6': .\ZJU_Courses\CSbasic\ADS\spring\Lecture\6.md
          - '7': .\ZJU_Courses\CSbasic\ADS\spring\Lecture\7.md
          - '8': .\ZJU_Courses\CSbasic\ADS\spring\Lecture\8.md
        - review:
          - 0_AMOZIZE: .\ZJU_Courses\CSbasic\ADS\spring\review\0_AMOZIZE.md
          - 1_AVL&SPLAY: .\ZJU_Courses\CSbasic\ADS\spring\review\1_AVL&SPLAY.md
          - 2_RBT&B+: .\ZJU_Courses\CSbasic\ADS\spring\review\2_RBT&B+.md
          - 3_FIle: .\ZJU_Courses\CSbasic\ADS\spring\review\3_FIle.md
          - 4_HEAP: .\ZJU_Courses\CSbasic\ADS\spring\review\4_HEAP.md
          - 5_QUEUE: .\ZJU_Courses\CSbasic\ADS\spring\review\5_QUEUE.md
          - midTerm: .\ZJU_Courses\CSbasic\ADS\spring\review\midTerm.md
          - pta: .\ZJU_Courses\CSbasic\ADS\spring\review\pta.md
          - 数据结构待实现清单: .\ZJU_Courses\CSbasic\ADS\spring\review\数据结构待实现清单.md
          - 期中知识点: .\ZJU_Courses\CSbasic\ADS\spring\review\期中知识点.md
      - summer:
        - '10': .\ZJU_Courses\CSbasic\ADS\summer\10.md
        - '11': .\ZJU_Courses\CSbasic\ADS\summer\11.md
        - '9': .\ZJU_Courses\CSbasic\ADS\summer\9.md
      - 前言: .\ZJU_Courses\CSbasic\ADS\前言.md
    - CO:
      - EXP:
        - '0': .\ZJU_Courses\CSbasic\CO\EXP\0.md
        - '1': .\ZJU_Courses\CSbasic\CO\EXP\1.md
      - spring:
        - lecture:
          - 1+2.1: .\ZJU_Courses\CSbasic\CO\spring\lecture\1+2.1.md
          - '2.2': .\ZJU_Courses\CSbasic\CO\spring\lecture\2.2.md
          - '3': .\ZJU_Courses\CSbasic\CO\spring\lecture\3.md
          - '4.1': .\ZJU_Courses\CSbasic\CO\spring\lecture\4.1.md
          - '4.2': .\ZJU_Courses\CSbasic\CO\spring\lecture\4.2.md
          - '5': .\ZJU_Courses\CSbasic\CO\spring\lecture\5.md
          - '6': .\ZJU_Courses\CSbasic\CO\spring\lecture\6.md
          - '7': .\ZJU_Courses\CSbasic\CO\spring\lecture\7.md
          - '8.2': .\ZJU_Courses\CSbasic\CO\spring\lecture\8.2.md
          - '8': .\ZJU_Courses\CSbasic\CO\spring\lecture\8.md
        - review:
          - '1': .\ZJU_Courses\CSbasic\CO\spring\review\1.md
          - '2.1': .\ZJU_Courses\CSbasic\CO\spring\review\2.1.md
          - '2.2': .\ZJU_Courses\CSbasic\CO\spring\review\2.2.md
          - '2.3': .\ZJU_Courses\CSbasic\CO\spring\review\2.3.md
          - '2.4': .\ZJU_Courses\CSbasic\CO\spring\review\2.4.md
          - '2.5': .\ZJU_Courses\CSbasic\CO\spring\review\2.5.md
          - '3': .\ZJU_Courses\CSbasic\CO\spring\review\3.md
          - graphic: .\ZJU_Courses\CSbasic\CO\spring\review\graphic.md
          - hw: .\ZJU_Courses\CSbasic\CO\spring\review\hw.md
      - summer:
        - 9.md: .\ZJU_Courses\CSbasic\CO\summer\9.md.md
      - 前言: .\ZJU_Courses\CSbasic\CO\前言.md
    - DBS:
      - JDBC:
        - '1': .\ZJU_Courses\CSbasic\DBS\JDBC\1.md
        - lab5: .\ZJU_Courses\CSbasic\DBS\JDBC\lab5.md
      - review:
        - '1': .\ZJU_Courses\CSbasic\DBS\review\1.md
        - '2': .\ZJU_Courses\CSbasic\DBS\review\2.md
        - '3.5': .\ZJU_Courses\CSbasic\DBS\review\3.5.md
        - '3': .\ZJU_Courses\CSbasic\DBS\review\3.md
        - '4': .\ZJU_Courses\CSbasic\DBS\review\4.md
        - '6': .\ZJU_Courses\CSbasic\DBS\review\6.md
      - spring:
        - '2': .\ZJU_Courses\CSbasic\DBS\spring\2.md
        - '3': .\ZJU_Courses\CSbasic\DBS\spring\3.md
        - '4': .\ZJU_Courses\CSbasic\DBS\spring\4.md
        - '5': .\ZJU_Courses\CSbasic\DBS\spring\5.md
        - '6': .\ZJU_Courses\CSbasic\DBS\spring\6.md
        - '7': .\ZJU_Courses\CSbasic\DBS\spring\7.md
        - '8': .\ZJU_Courses\CSbasic\DBS\spring\8.md
        - Chap1: .\ZJU_Courses\CSbasic\DBS\spring\Chap1.md
      - summer:
        - '10': .\ZJU_Courses\CSbasic\DBS\summer\10.md
        - '11': .\ZJU_Courses\CSbasic\DBS\summer\11.md
        - '9': .\ZJU_Courses\CSbasic\DBS\summer\9.md
      - 前言: .\ZJU_Courses\CSbasic\DBS\前言.md
    - DM:
      - DM: .\ZJU_Courses\CSbasic\DM\DM.md
      - hw1: .\ZJU_Courses\CSbasic\DM\hw1.md
      - note0: .\ZJU_Courses\CSbasic\DM\note0.md
    - English:
      - Vocabulary:
        - sentence: .\ZJU_Courses\CSbasic\English\Vocabulary\sentence.md
        - word: .\ZJU_Courses\CSbasic\English\Vocabulary\word.md
      - Writing:
        - sentence: .\ZJU_Courses\CSbasic\English\Writing\sentence.md
        - word: .\ZJU_Courses\CSbasic\English\Writing\word.md
    - FDS:
      - qianyan: .\ZJU_Courses\CSbasic\FDS\qianyan.md
      - 图: .\ZJU_Courses\CSbasic\FDS\图.md
      - 基础知识: .\ZJU_Courses\CSbasic\FDS\基础知识.md
      - 排序: .\ZJU_Courses\CSbasic\FDS\排序.md
      - 树: .\ZJU_Courses\CSbasic\FDS\树.md
      - 线性结构: .\ZJU_Courses\CSbasic\FDS\线性结构.md
      - 题目: .\ZJU_Courses\CSbasic\FDS\题目.md
    - OOP:
      - 2- Using Objects:
        - Chap1: .\ZJU_Courses\CSbasic\OOP\2- Using Objects\Chap1.md
        - Const: .\ZJU_Courses\CSbasic\OOP\2- Using Objects\Const.md
        - DMA: .\ZJU_Courses\CSbasic\OOP\2- Using Objects\DMA.md
        - File: .\ZJU_Courses\CSbasic\OOP\2- Using Objects\File.md
        - Reference: .\ZJU_Courses\CSbasic\OOP\2- Using Objects\Reference.md
        - String: .\ZJU_Courses\CSbasic\OOP\2- Using Objects\String.md
      - 3-Class:
        - Makefile: .\ZJU_Courses\CSbasic\OOP\3-Class\Makefile.md
        - Object: .\ZJU_Courses\CSbasic\OOP\3-Class\Object.md
      - 4-Object Interactive:
        - C'tor and D'tor: .\ZJU_Courses\CSbasic\OOP\4-Object Interactive\C'tor and
            D'tor.md
      - 6-Copy Ctor:
        - '1': .\ZJU_Courses\CSbasic\OOP\6-Copy Ctor\1.md
      - Const: .\ZJU_Courses\CSbasic\OOP\Const.md
      - 前言: .\ZJU_Courses\CSbasic\OOP\前言.md
    - Programming Language:
      - C++ Programming Tutorial:
        - '0': .\ZJU_Courses\CSbasic\Programming Language\C++ Programming Tutorial\0.md
        - '1': .\ZJU_Courses\CSbasic\Programming Language\C++ Programming Tutorial\1.md
        - '2': .\ZJU_Courses\CSbasic\Programming Language\C++ Programming Tutorial\2.md
        - '3': .\ZJU_Courses\CSbasic\Programming Language\C++ Programming Tutorial\3.md
        - gccmake: .\ZJU_Courses\CSbasic\Programming Language\C++ Programming Tutorial\gccmake.md
        - reference: .\ZJU_Courses\CSbasic\Programming Language\C++ Programming Tutorial\reference.md
      - Java:
        - 基本语法: .\ZJU_Courses\CSbasic\Programming Language\Java\基本语法.md
        - 编译逻辑: .\ZJU_Courses\CSbasic\Programming Language\Java\编译逻辑.md
      - Python:
        - '0': .\ZJU_Courses\CSbasic\Programming Language\Python\0.md
        - '1': .\ZJU_Courses\CSbasic\Programming Language\Python\1.md
    - SRTP:
      - eai:
        - DL: .\ZJU_Courses\CSbasic\SRTP\eai\DL.md
        - ML_algr: .\ZJU_Courses\CSbasic\SRTP\eai\ML_algr.md
        - ML_index: .\ZJU_Courses\CSbasic\SRTP\eai\ML_index.md
        - ML_method: .\ZJU_Courses\CSbasic\SRTP\eai\ML_method.md
    - 同学们应该都有过在中国铁路12306网站抢订火车票的经历。: .\ZJU_Courses\CSbasic\同学们应该都有过在中国铁路12306网站抢订火车票的经历。.md
    - 数字逻辑设计:
      - shuluo: .\ZJU_Courses\CSbasic\数字逻辑设计\shuluo.md
  - math:
    - shufen1:
      - 不要忘记反证法: .\ZJU_Courses\math\shufen1\不要忘记反证法.md
  - 其它有意思的课程:
    - 习概:
      - '0': .\ZJU_Courses\其它有意思的课程\习概\0.md
    - 无线网络应用:
      - 无线网络应用: .\ZJU_Courses\其它有意思的课程\无线网络应用\无线网络应用.md
    - 生命科学导论(H):
      - '1': .\ZJU_Courses\其它有意思的课程\生命科学导论(H)\1.md
      - 前言: .\ZJU_Courses\其它有意思的课程\生命科学导论(H)\前言.md
    - 马原:
      - 马原: .\ZJU_Courses\其它有意思的课程\马原\马原.md
  - 前言: .\ZJU_Courses\前言.md
